name: Auto Releases

on:
  workflow_dispatch:
  
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    name: Check, build, release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Clone Celeritas
        run: git clone https://git.taumc.org/embeddedt/celeritas.git

      - name: Check for updates
        id: check
        working-directory: ./celeritas
        run: |
          CURRENT_COMMIT=$(git rev-parse HEAD)
          PREVIOUS_COMMIT=$(cat ../latest_commit)

          echo "Current commit: $CURRENT_COMMIT"
          echo "Previous commit: $PREVIOUS_COMMIT"

          if [[ "$CURRENT_COMMIT" == "$PREVIOUS_COMMIT" ]]; then
            echo "Celeritas has not changed."
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "Celeritas has changed."
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

          echo "commit=$CURRENT_COMMIT" >> "$GITHUB_OUTPUT"

      - name: Stop if Celeritas has no updates
        if: steps.check.outputs.changed == 'false'
        run: echo "Nothing to build."

      - name: Get release information
        id: info
        if: steps.check.outputs.changed == 'true'
        working-directory: ./celeritas
        run: |
          echo "describe=$(git describe --tags | sed "s/-g[0-9a-f]*$//")" >> "$GITHUB_OUTPUT"

      - name: Create release notes
        if: steps.check.outputs.changed == 'true'
        working-directory: ./celeritas
        run: |
          CURRENT_COMMIT="${{ steps.check.outputs.commit }}"
          PREVIOUS_COMMIT=$(cat ../latest_commit)

          echo "## What's Changed" >> body.md
          git rev-list $PREVIOUS_COMMIT..$CURRENT_COMMIT --no-commit-header --format="format:- %s by **[@%an](https://git.taumc.org/%an)**" --reverse >> body.md
          echo >> body.md
          echo "### [Full Changelog](https://git.taumc.org/embeddedt/celeritas/compare/$PREVIOUS_COMMIT..$CURRENT_COMMIT)" >> body.md

      - name: Set up JDK
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: |
            8
            21
            
      - name: Build all versions
        if: steps.check.outputs.changed == 'true'
        working-directory: ./celeritas
        run: |
          chmod +x ./gradlew
          ./gradlew -Pceleritas_target_versions_pattern=1.20.1 packageJar

      - name: Update latest commit hash
        if: steps.check.outputs.changed == 'true'
        run: echo "${{ steps.check.outputs.commit }}" > latest_commit

      - name: Commit latest commit hash
        if: steps.check.outputs.changed == 'true'
        uses: EndBug/add-and-commit@v10
        with:
          add: latest_commit
          push: true
          tag: "${{ steps.info.outputs.describe }}"

      - name: Create GitHub release
        if: steps.check.outputs.changed == 'true'
        uses: ncipollo/release-action@v1.21.0
        with:
          artifacts: "celeritas/build/libs/**/*.jar"
          bodyFile: "celeritas/body.md"
          generateReleaseNotes: false
          tag: "${{ steps.info.outputs.describe }}"
